# Configuração do terraform-docs para gerar documentação em formato Markdown

formatter: markdown          # O formato da documentação gerada (pode ser markdown, html, json, etc.)

output:
  # Definindo o arquivo de saída e as seções a serem incluídas
  file: README.md             # O arquivo de saída onde a documentação será escrita
  sections:
    - outputs
    - inputs
    - providers
    - resources
    - modules
    - dependencies

# Alterado para que header-from e footer-from sejam arquivos diferentes
header-from: ../docs/HEADER-1.md       # Arquivo de cabeçalho para incluir no início da documentação
footer-from: ../docs/FOOTER-1.md       # Arquivo de rodapé para incluir no final da documentação

sort:
  # Ordena os recursos do Terraform (por exemplo, variáveis, outputs) de forma alfabética
  resources: true
  outputs: true
  variables: true

sections:
  # Controla quais seções serão incluídas na documentação gerada
  terraform-version: true    # Versão do Terraform usada
  providers: true            # Exibe os provedores utilizados no módulo
  inputs: true               # Exibe as variáveis de entrada (inputs)
  outputs: true              # Exibe as variáveis de saída (outputs)
  resources: true            # Exibe os recursos do Terraform no módulo
  footer: true               # Inclui o rodapé no arquivo de documentação

# Inclui uma lista de arquivos para serem excluídos da documentação
exclude:
  - "*.tfstate"
  - "*.tfstate.*"
  - ".terraform"

# Configurações de formatação personalizadas
style:
  heading: true               # Exibe títulos (headings) em negrito
  subheading: true            # Exibe subtítulos (subheadings) em itálico
  tables: true                # Exibe tabelas em formato Markdown
  code-blocks: true           # Exibe blocos de código com formatação
